# Generated by Django 4.1.3 on 2024-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_tag_rename_name_skill_title_skill_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
