# Generated by Django 4.1.3 on 2024-01-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_skill_body_skill_per"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="slug",),
    ]
