# Generated by Django 4.1.3 on 2024-01-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_project_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill", old_name="per", new_name="percentage",
        ),
    ]
