# Generated by Django 4.1.3 on 2024-01-30 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_per_skill_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program_language",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("percentage", models.IntegerField(default=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Soft_skills",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("percentage", models.IntegerField(default=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("percentage", models.IntegerField(default=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(old_name="Skill", new_name="Framework",),
    ]
