# Generated by Django 4.1.3 on 2024-01-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_program_language_soft_skills_technology_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Technology", new_name="Framework_Skills",),
        migrations.RenameModel(old_name="Framework", new_name="Technology_Skills",),
    ]
