# Generated by Django 4.1.3 on 2024-01-31 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_rename_technology_framework_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                ("collage", models.CharField(max_length=200, null=True)),
                ("degree", models.CharField(max_length=200, null=True)),
                ("field", models.CharField(max_length=200, null=True)),
                ("date", models.CharField(max_length=200, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
