# Generated by Django 4.1.3 on 2024-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education", old_name="field", new_name="major",
        ),
        migrations.AddField(
            model_name="education", name="gpa", field=models.IntegerField(default=3.5),
        ),
    ]
