# Generated by Django 4.1.3 on 2024-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_rename_field_education_major_education_gpa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="gpa",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
