# Generated by Django 4.1.3 on 2024-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_education_gpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="image",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
