# Generated by Django 4.1.3 on 2024-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_education_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("date", models.CharField(max_length=200, null=True)),
                ("detail", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
