# Generated by Django 4.1.3 on 2024-02-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience", old_name="date", new_name="company_name",
        ),
        migrations.AddField(
            model_name="experience",
            name="end",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="start",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
