# Generated by Django 4.1.3 on 2024-02-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_rename_date_experience_company_name_experience_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="detail",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
